[package]
name = "mx25r"
version = "0.1.0"
edition = "2021"
authors = ["xgroleau <grox2901@usherbrooke.ca>"]
repository = "https://github.com/xgroleau/mx25r-rs"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/xgroleau/mx25r-rs"
description = "Platform-agnostic Rust driver for the macronix MX25R NOR flash."
documentation = "https://docs.rs/mx25r"
readme = "README.md"
keywords = ["nor-flash", "spi", "driver", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Migrate to embedded-hal repo
embedded-hal = { package = "embedded-hal", version = "1.0.0-alpha.7", git = "https://github.com/embassy-rs/embedded-hal", branch = "embassy2" }
bit = "0.1.1"
defmt = { version = "0.3", optional = true }
embedded-storage = "0.3.0"