[package]
name = "mx25r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: Migrate to embedded-hal repo
embedded-hal = { package = "embedded-hal", version = "1.0.0-alpha.7", git = "https://github.com/embassy-rs/embedded-hal", branch = "embassy2" }
bit = "0.1.1"
defmt = { version = "0.3", optional = true }
